AnyChange:
- changed-files:
  - any-glob-to-any-file: '**'

Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

action:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/**]
- head-branch: ['^action', 'action', 'action-*']

feature:
- head-branch: ['^feature', 'feature', 'feature-*']

release:
- base-branch: 'master'
- head-branch: 'dev'
