documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

actions:
- changed-files:
  - any-glob-to-any-file: '.github/**'

bug:
  - head-branch: ['*patch*', '^bravegrumpy-patch', '^bug', '^bugfix']

enhancement:
  - head-branch: ['^feature', 'feature', 'feature-*']

release:
  - base-branch: 'master'
  - head-branch: 'dev'
