documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

workflow:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**]

bug:
  - head-branch: ['*-patch-*', '^bug', '^bugfix']

enhancement:
  - head-branch: ['^feature', 'feature', 'feature-*']

release:
  - all:
    - base-branch: 'master'
    - head-branch: 'dev'
